name: environment
channels:
  - damianavila82
  - conda-forge
dependencies:
    - python 
    - numpy
    - matplotlib
    - scipy
    - widgetsnbextension
    - ipywidgets
    - pandas
    - bokeh
    - rise


